package com.pragma.arquetipobootcamp2024.adapters.driven.jpa.mysql.entity;

import lombok.Data;

import javax.persistence.*;


//contains the classes that represent the tables in your database


@Data // automatically generates methods such as getters, setters, equals(), hashCode() and toString().
@Entity // indicates that this class is a JPA entity, will be mapped to a database
@Table(name = "categories") // specifies the name of the table in the database
public class CategoryEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //This specifies that the value of the id field will be automatically generated by the database.
    private Long id;


    //@Column(I define the column with the necessary restrictions)
    @Column(nullable = false, unique = true, length = 50) // cannot be null, there can be no begging, 50 characters maximum
    private String name;

    @Column(nullable = true, length = 90) // cannot be null, 90 characters maximum
    private String description;


}
